### ISSUE TITLE
Empty Captions in PDF Output

### ISSUE THREAD

**Issue by dsanson** [nichtich/ditaa-markdown#1]
First, this is a great little script. Thanks for it!

One issue I've noticed is that the ditaa images get transformed into links that look like this

```
![](image-1.pdf)
```

and since these links are alone on a line, pandoc tries to use the alt text as the figure caption, leading to empty captions. One workaround is to make certain that the image link is not alone on a line, by, for example, adding an escaped space, e.g.,

```
![](image-1.pdf)\ 
```

I've made that change on [my fork](https://github.com/dsanson/ditaa-markdown). But it would be even nicer to be able to specify that alt text somehow. Perhaps something like

```
~~~ {.ditaa "My Image"}
```

would work? That might not be consistent with the other thing I am about to propose as a separate issue.

**Comment by nichtich** [comment]
I commented on https://github.com/nichtich/ditaa-markdown/issues/2
